_darb ; blow ; n
riba.h ; profit ; n
rukn ; corner ; n 
ba.tal ; hero ; n 
fur^saT; brush ; n 
taaj ; crown ; n
marraT ; time, occasion ; n
rattab ; arrange ; v
.saali.h ; righteous ; a
^sujaa` ; brave ; a 
kalaam ; speech ; n 
kariym ; generous ; a
ra'uwf ; compassionate ; a
'a.sla` ; bald ; a 
.sa.hraa' ; desert ; n 
'a.sdiqaa' ; friends ; n 
'a.tibbaa' ; doctors ; n 
.tayaraan ; aviation ; n
tim_taal ; statue ; n
ta`liym ; education ; n 
taqaddum ; progress ; n 
minbar ; pulpit ; n
miknasaT ; broom ; n 
miftaa.h ; key ; n
isti`laam ; enquiry ; n 
imti.haan ; exam ; n 
inqilaab ; coup d'etat ; n 
dam ; blood ; n 
zalzalaT ; earthquake ; n 
zumurrud ; emerald ; n 
^sa.tranj ; chess ; n 
banafsaj ; violet ; n 

