.taalib  ( .talabaT, .tullab ) ; student ; n 
kaatib ( katabaT, kuttaab ) ; clerk ; n 
.sunduwq ( .sanaadiyq ) ; box, trunk ; n 
dawlab ( dawliyb ) ; cupboard ; n 
saa'iyq ( suwwaaq, saa'iyquwn ) ; driver ; n 
sikritayr ; secretary ; n 
kalb ( kilaab ) ; dog ; n 
.haakim ( .haakimuwn, .hukkaam ) ; ruler ; n 
.sahn ( .suhuwn ) ; plate, dish ; n 
taajir ( tujjaar ) ; merchant, shopkeeper ; n 
mat.haf ( mataa.hif ) ; museum ; n 
muwa.z.zaf ( muwa.z.zafuwn ) ; employee, official ; n 
`aadil ; just ; a
.saa.tir ; clever  ; a
jamiyl ; beautiful, handsome ; a
samiyn ; fat ; a
.gaa'iyb ; absent ; a
qariyb ; near ; a
.haa.dir ; present ; a
mamluw' ; full ; a
_taqiyl ; heavy ; a
_hafiyf ; light ; a
faari.g ; empty ; a
maksuwr ; broken ; a


