qalaam ( 'aqlaam )  ; pencil, pen ; n
waraqaT ( aat ) ; sheet of paper ; n
ma.sna` ( ma.saani` ) ; factory ; n
nuktaT ( nukat ) ; joke ; n
ni.sf ( 'an.saaf ) ; half ; n
saa`aT ( aat) ; hour, clock, watch ; n
rub` ( 'arba` ) ; quarter ; n
_tul_t ( 'a_tlaa_t ) ; third ; n
manzil ( manaazil ) ; house, dwelling ; n
`aamil ( `ummaal ) ; worker ; n
'i`laan ( aat ) ; announcement ; n
majlis ( majaalis ) ; council ; n
majallaT ( aat ) ; magazine ; n
jariydaT ( jara'id ) ; newspaper ; n
ma.sdar ( ma.saadir ) ; source ; n
.taa'iraT ( aat ) ; aeroplane ; n
ma.tna`aT ( aat ) ; printing house ; n
min.taqaT ( manaa.tiq ) ; area, zone ; n
maa' ( miyaah ) ; water ; n
^sajaraT ( 'a^sjaar ) ; tree ; n
.hukumaT ( aat ) ; government ; n
sinimaa ( sinimaat ) ; cinema ; n
qism ( 'aqsaam ) ; department ; n
wizaaraT ( aat ) ; ministry ; n
jadiyd ; new ; a 
mujtahid ; diligent, hard working ; a 
haamm ; important ; a 
'usbuw`iyy ; weekly ; a 
_taqafiyy ; cultural ; a 
_hadiy_t ; modern ; a 
yawmiyy ; daily ; a 
`aamm ; general ; a 
ra'iysiyy ; main, principal ; a 
kaslaan ; lazy, idle ; a 
_ha.s.s ; special ; a 
'illaa ; except ; o 
kam ; how many? ; o
