musaafir ( wn ) ; traveller ; n
.haffar ( wn ) ; driller ; n
`aa.simaT ( `awaa.sim ) ; capital city ; n
jumruk ( jamaarik ) ; customs  ; n
.saa.hb ( 'a.s.haab ) ; friend ; n
imra'aT ( almar'aT nisa' ) ; woman ; n
.sadiyq ( 'a.sdiqaa' ) ; friend ; n
maqaalaT ( aat) ; article ; n
ka_d_daab ( wn ) ; liar ; n
rassaam ( wn ) ; painter, artist ; n
la.h.haam ( wn ) ; welder ; n
dabbaabaT ( aat ) ; tank ; n
najjar ( wn ) ; carpenter ; n
.hammaal ( wn ) ; porter ; n
.tabbaa_h ( wn ) ; cook ; n
mu.haasib ( wn ) ; accountant ; n
muqaawil ( wn ) ; contractor ; n
_habbaaz ( wn ) ; baker ; n
kahrabaa'iy ( wn ) ; electrician ; n
mumarra.daT ( aat ) ; nurse ; n
.dayf ( .duyuwf ) ; guest ; n
raakib ( rukaab ) ; passenger ; n
dabbaasaT ( aat ) ; stapler ; n
_tallaajaT ( aat ) ; fridge ; n
jabiyr ; experienced, expert ; n
ka_tiyr ( wn ) ; much, many ; a
kaamil ; complete ; a
qaliyl ( wn ) ; little, few ; a
faqiyr ( fuqaraa' ) ; poor ; a
mi.sri_A_A ( wn ) ; egyptian ; a
.haziyn ( hazaana_A ) ; sad ; a
maahir ( wn ) ; skilled  ; a
mu.gaadir ( wn ) ; departing ; a
sariy` ( siraa` ) ; quick, fast ; a
qara'a ; read ; v
fatta^s ; examine, search  ; v
.talab ; request, ask for ; v
i^sta.gal ; work ; v
'arsal ; send ; v
kasab ; earn, gain ; v
_dahab ; go ; v
sa'al ; ask ; v


 

