bayt ( buyuwt ) ; house ; n
rajul ( rijaal ) ; man ; n
kitaab ( kutub ) ; book ; n
baab ( 'abwaab ) ; door ; n
mudiyr ( mudiyruwn ) ; manager ; n
^saari` ( ^sawaari` ) ; street ; n
walad ( 'awlaad ) ; boy ; n
maktab ( makaatib )  ; desk, office ; n
^subbaak ( ^sabaabiyk ) ; window ; n
ma.tar ( ma.taaraat ) ; airport ; n
.tawiyl ; long, tall ; a
qa.siyr ; small ; a
kabiyr ; big, old ; a
.sa.giyr ; small, young ; a
ma^s.guwl ; busy ; a
waasi` ; spacious ; a
naafi` ; useful ; a
ma^shuwr ; famous ; a
na.hiyf ; thin ; a
ba`iyd ; far, distant ; a
`ariy.d ; wide ; a
na.ziyf ; clean ; a
