muslim ( wn ) ; muslim ; n
`iyd ( 'a`yaad ) ; festival ; n
ism ( 'asmaa' ) ; name ; n
i_tnaan ; two ; n
^sawwaal ; shawwal month ; n
fi.tr ; breaking of fast ; n
rama.daan ; ramadan month ; n
munaasabaT ( aat ) ; occasion ; n
ma`na_A ; meaning ; n 
.sawm ; fast ; n
nahaar ; daytime ; n
naas ; people ; n
_hajj ; pilgrimage ; n
al'a.d.ha_A ; sacrifice festival ; n
makkaT ; mecca ; n
`aadaT ( aat ) ; custom ; n
_dabiy.haT ( _dabaa'i.h ) ; slaughter animal ; n
ka`baT ; Kaaba shrine ; n
nihaayaT ; end ; n
_haruwf ( _hirfaan ) ; sheep ; n
nabiy ( 'anbiyaa' ) ; prophet ; n
mawlid ; mulid ; n
masiy.hiyy ( wn ) ; christian ; n
qu.tr ( 'aq.taar ) ; part, area, region ; n
miylaad ; birth ; n
rabiy` al'awwal ; rabi month ; n
`iyd almiylaad ; christmas ; n
`iyd miylaad ; birthday ; n
zaar, yazuwr ; visit ; v
bada'a ; begin ; v 
i.htafal bi, ya.htafil bi ; celebrate ; v 
_daba.h ; slaughter ; v
`aqab ; follow ; v
muhimm ; important ; a
_tali_t ; third ; a
'a_A_A ; which ; o
maa ; what ; o
'anna ; that ; o
kayf ; how ; o
i_daa ; then ; o
faqa.t ; only ; o
mi_tl ; like ; o
na`.d ; some ; o
'aw ; or ; o
fa ; so ; o

