raja` ; return ; v
saafar ; travel ; v
da_hal ; enter ; v
fata.h ; open ; v
'ad_hal ; admit, cause to enter ; v
dafa` ; push, pay ; v
'akal ; eat ; v
rafa.d ; refuse ; v
kallam ; speak to, address someone ; v
^sarib ; drink ; v
'a`lan ; announce ; v
.taba.h ; cook ; v
ijtama` ; meet ; v
'a.drab ; strike ; v
wa.da` ; place ; v
inta_hab ; elect ; v
'ajlas ; seat someone, cause to sit ; v
wa.dal ; arrive ; v
katab ; write ; v
wajad ; find ; v

alba.hriyn ; Bahrain ; n 
alkuwiyt ; Kuwait ; n 
fuluws ; money  ; n 
alriyaa.d ; Riyadh ; n 
.ta`aam ( 'a.t`imaT ) ; food ; n 
zawjaT ( aat ); wife ; n 
`alaawaT ; raise ; n 
inti.haab ( aat ) ; election ; n 
.sabaa.h ; morning ; n 
^san.taT ( ^suna.t ) ; case, briefcase ; n 
taqriyr ( taqaariyr ) ; report ; n 
ra'iys ( ru'usaa' ) ; chief, boss ; n 
daftar ( dafaatir ) ; file ; n 
ra'iys alwuzaraa' ; prime minister ; n 
_tumma ; then ; o 
'ila_A ; to, towards ; p 
maa ; not ; o 
'ums ; yesterday ; o
