qamiy.s ( qum.saan ) ; shirt ; n 
jaami`aT ( aat ) ; university ; n 
waziyr ( wuzaraa' ) ; minister ; n 
aldaa_hiliyyaT ; interior ; n 
la.hm ( lu.huwm ) ; meat ; n 
qi.ta`aT ( qi.ta` ) ; piece ; n 
natiyjaT ( nataa'ij ) ; result ; n 
rawaayaT ( aat ) ; novel ; n 
du_huwl ; entering, entrance ; n 
sayaasaT ( aat ) ; policy ; n 
kiluw.graam ( aat ) ; kilogram ; n 
jadiyqaT ( jadaa'iq ) ; garden ; n 
_hubz ; bread ; n 
daqiyq ; flour ; n 
.harf ( .hufuwf ) ; letter ; n 
wa.ziyfaT ( wa.zaa'if ) ; job, function ; n 
bank ( bunuwk ) ; bank ; n 
ra's ( ru'uws ) ; head ; n 
_huruwj ; exit ; n 
.tard ( .turuwd ) ; parcel ; n 
rujuw` ; return ; n 
far` ( furuw` ) ; branch ; n 
fustaan ( fasaatiyn ) ; dress ; n 
ba_dlaT ( ba_dal ) ; suit ; n 
bitruwl ; crude oil ; n 
^sarikaT ( aat ) ; company ; n 
`ajiyb ; wonderful ; a
.gariyb ; strange ; a
sahl ; easy ; a
.sa`b ; difficult ; a
ra_hiy.s ; cheap ; a
markaziyy ; central ; a
'ajnabiyy ; foreign ; a
ma.halliyy ; local ; a

