landan ; london ; n
^saqqaT ( ^siqaq ) ; flat, apartment ; n
^sahr ( 'a^shur, ^suhuwr ) ; month ; n
'i.h.saa'iyaat ; statistics ; n
raq.s ; dance ; n
fariyq ( 'afriqaT ) ; troupe, team ; n
.saadiraat ; exports ; n
^say' ( 'a^syaa' ) ; thing ; n
waridaat ; imports ; n
wa.tan ( 'aw.taan ) ; homeland ; n
junayT ( aat ) ; pound ; n
qahwaT; coffee ; n
al-ll_ah ; God ; n
lu.gaT ( aat ) ; language ; n
'amiyr ( 'umaraa' ) ; prince ; n
safiyr ( sufaraa' ) ; ambassador ; n
'adiyb ( 'udabaa' ) ; writer ; n
_habiyr ( _hubaraa' ) ; expert ; n
`askar_A ( `asaakir ) ; soldier, policeman ; n
ba_hiyl ( bu_halaa' ) ; miser ; n
daras ; study ; v
na^sar ; publish ; v
`araf ; know, come to know ; v
qaddam, yuqaddim ; present ; v
daafa' `an, yudaafi` `an ; defend ; v
.da.hik ; laugh ; v
raqa.s ; dance ; v
sakan ; dwell, live in ; v
.hamal ; carry ; v
fahil ; understand ; v
la`ib ; play ; v
.saraf ; spend ; v
rasmiya ; official ; a 
qawmiyy ; national ; a
a_har ( 'u_hra_A ) ; other ; a
^sa`biyy ; folk ; a
injiliyz_A_A ; english ; a
`arabiyy ; arab, arabic ; a
a_hir ; last ; a
'uwwal ( 'uwl_A ) ; first ; a
.gadaa ; tomorrow ; a
'abadaa ; never ; a
qabl ; before ; p
na`d ; after ; p
taht ; below ; p
li ; to, for ; p
`an ; from, of, about ; p
lada_A ; with ; p 
maa_daa ; what ; o 
bi ; with, by means of, by ; p 
ka_tiraa ; a lot, much ; a
