sikritiyraT ( aat ) ; secretary ; n
bint ( banaat ) ; girl ; n
_hayyaa.t  ( wn ) ; tailor ; n
raff ( rufuwf ) ; shelf ; n
zaa'ir ( zuwwaar ) ; visitor ; n
madrasaT ( madaaris ) ; school ; n
.gurfaT ( .guraf ) ; room ; n
kalimaT ( aat ) ; word ; n
sayyaaraT ( aat ) ; car ; n
i^stiraakiyaT ; socialism ; n
kitaabaT ; writing ; n
maktabaT ( aat) ; library, bookshop ; n
'umm ( 'ummahat ) ; mother ; n
'u_ht ( 'a.hawat ) ; sister ; n
yad ( 'ayaad ) ; hand ; n
^sams ( ^sumuws ) ; sun ; n
suwq ( 'aswaaq ) ; market ; n
.harb ( .hurub ) ; war ; n
manduwn ( uwn) ; delegate ; n
ma^sruw` ( aat ) ; project ; n
.taawilaT ( aat ) ; table ; n
'ar.d ( 'araa.d ) ; ground ; n
madiynaT ( mudun ) ; town, city ; n
kursiyy ( karaasiy ) ; chair ; n
jaami` ( jawaami` ) ; large mosque ; n
masjid ( masaajid ) ; mosque ; n
jayyad ; good ; a
.harr ; hot, burning ; a
mansuw.t ; pleased ; a
majnuwn ; mad ; a
maqfuwl ; closed ; a
majruw.h ; wounded, injured ; a
wasi_h ; dirty ; a
maftuw.h ; open ; a
fiy ; in ; p
`al_A ; on ; p 
min ; from ; p 
farqa ; above, on top of ; p 
`inda ; near, with, 'chez' ; p 
ma`a ; together with ; p