yawm ( 'ayaam ) ; day ; n 
masra.h ( masaari.h ) ; theatre ; n 
qaa'id ( quwwaad, qaadaT ) ; leader ; n 
muhandis ( wn ) ; engineer ; n 
yawm al'a.had ; sunday ; n 
yawm aali_tnayn ; monday ; n 
yawm al_talaa_tl' ; tuesday ; n 
yawm al'arba`aa' ; wednesday ; n 
yawm al_hamiys ; thursday ; n 
yawm aljum`aT ; friday ; n 
yawm alsabt ; saturday ; n 
barnaamaj ( baraamij ) ; programme ; n 
.tifl ( 'a.tfaal ) ; child, baby ; n 
malik ( muluwk ) ; king ; n 
jabbaar ( jabaabiraT ) ; tyrant ; n 
'amr ( 'umuwr ) ; matter ; n 
mu.harrir ( wn ) ; editor ; n 
wafd ( wufuwd ) ; delegation ; n 
muma_t_til ( wn ) ; representative ; n 
tartiyb ( aat ) ; arrangement ; n 
dubay ; dubai ; n 
ta`liym ; education ; n 
mu.hammad ; muhammad ; n 
tamriyn ( tamaariyn ) ; exercise ; n 
muna.z.zim ( wn ) ; organiser ; n 
mudarris ( wn ) ; teacher ; n 
jamaal `bd alnaa.sr ; gamal abdul nasser ; n 
mufatti^s ( wn ) ; inspector ; n 
mu`aqqad ; complicated ; a
`a.ziym ; great, mighty ; a
munaasib ; suitable, fitting ; a
_dakiy ; clever, intelligent ; a
jaahil ; ignorant ; a
faa^sil ; futile ; a
laysa ; is not, are not ; v
kaan ; was, were ; v
darras ; teach ; v 
'a.sba.h ; become ; v
wa.z.zafa ; appoint, employ ; v 
.saar ; become ; v 
'a_ha_d ; take ; v
rattab ; arrange ; v

 



